function tdat = func_tsne(Dat_Pre)
    Dreduc_opts = cell(5,2);
    % Options for t-SNE
    Dreduc_opts(:,1) = {'Distance', ...
        'Algorithm', ...
        'Exaggeration', ...
        'Perplexity', ...
        'Theta'};
    % Defaults
    Dreduc_opts(:,2) = {'euclidean', ...
        'barneshut', ...
        '4', ...
        '30', ...
        '0.5'};
    
    
    dlg_title = 'Input Channel Arithmatics';
    num_lines = 1;
    vAnswer = inputdlg(Dreduc_opts(:,1),dlg_title,num_lines,Dreduc_opts(:,2));
    if isempty(vAnswer)
        return
    end
    Dreduc_opts(:,2) = vAnswer;

    % If X,Y,Z were included this breaks

    % Use t-sne to reduce the data to 2D
    tdat = tsne(Dat_Pre, ...
                Dreduc_opts{1, 1}, Dreduc_opts{1, 2}, ...
                Dreduc_opts{2, 1}, Dreduc_opts{2, 2}, ...
                Dreduc_opts{3, 1}, str2double(Dreduc_opts{3, 2}), ...
                Dreduc_opts{4, 1}, str2double(Dreduc_opts{4, 2}), ...
                Dreduc_opts{5, 1}, str2double(Dreduc_opts{5, 2}), ...
                'NumPCAComponents', 0);%<change back to 0
                        